# Generated by Django 3.0.7 on 2021-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisChargePatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=50)),
                ('doctorAssignedToPatient', models.CharField(max_length=50)),
                ('patientAddress', models.CharField(max_length=50)),
                ('patientContact', models.CharField(max_length=25, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('addmittedOn', models.DateField()),
                ('releaseOn', models.DateField()),
                ('daysSpent', models.PositiveIntegerField()),
                ('roomFee', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('consultationFee', models.PositiveIntegerField()),
                ('OtherCharges', models.PositiveIntegerField()),
                ('totalBill', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=25, null=True)),
                ('department', models.CharField(choices=[('Physician', 'Physician'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Physician', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=250)),
                ('chest_pain_type', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-anginal pain', 'Non-anginal pain'), ('Asymptomatic', 'Asymptomatic')], default='Typical Angina', max_length=250)),
                ('resting_blood_pressure', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('fasting_blood_sugar', models.IntegerField()),
                ('rest_ecg', models.CharField(choices=[('Normal', 'Normal'), ('ST-T wave abnormality', 'ST-T wave abnormality'), ('Left ventricular hypertrophy', 'Left ventricular hypertrophy')], default='Normal', max_length=250)),
                ('max_heart_rate_achieved', models.IntegerField()),
                ('exercise_induced_angina', models.IntegerField()),
                ('st_depression', models.FloatField(max_length=250)),
                ('st_slope', models.CharField(choices=[('Upsloping', 'Upsloping'), ('Flat', 'Flat'), ('Downslpoing', 'Downslpoing')], default='Upsloping', max_length=250)),
                ('target', models.CharField(default='No heart disease', max_length=250)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('address', models.CharField(max_length=100)),
                ('patientContact', models.CharField(max_length=25)),
                ('patientSymptoms', models.CharField(max_length=100)),
                ('admittedOn', models.DateField(auto_now=True)),
            ],
        ),
    ]
