# Generated by Django 3.0.7 on 2021-03-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210305_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select Gender', max_length=250)),
                ('chest_pain_type', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-anginal pain', 'Non-anginal pain'), ('Asymptomatic', 'Asymptomatic')], default='Typical Angina', max_length=250)),
                ('resting_blood_pressure', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('fasting_blood_sugar', models.IntegerField()),
                ('rest_ecg', models.CharField(choices=[('Normal', 'Normal'), ('ST-T wave abnormality', 'ST-T wave abnormality'), ('Left ventricular hypertrophy', 'Left ventricular hypertrophy')], default='Normal', max_length=250)),
                ('max_heart_rate_achieved', models.IntegerField()),
                ('exercise_induced_angina', models.IntegerField()),
                ('st_depression', models.FloatField(max_length=250)),
                ('st_slope', models.CharField(choices=[('Upsloping', 'Upsloping'), ('Flat', 'Flat'), ('Downslpoing', 'Downslpoing')], default='Upsloping', max_length=250)),
                ('rf', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=50)),
                ('ml', models.CharField(max_length=50)),
                ('rf_ped', models.CharField(max_length=250)),
                ('dt_pred', models.CharField(max_length=250)),
                ('ml_pred', models.CharField(max_length=250)),
                ('target', models.CharField(default='No heart disease', max_length=250)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
